# Generated by Django 4.1.5 on 2023-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
    ]
